serverKEY : KEYHERE
message-allow : "§cYou're not allowed to join."
message-fail : "§7To get whitelisted, please go to §emcsync.live"
message-error : "§cAn error has occured trying to access the whitelist API. Please contact the administrator." 