name: MCSync
main: mcsync.main
version: '1.2.0'
load: STARTUP
author: CaptinCornFlakes
website : https://mcsync.live
commands:
    mcsync:
        usage: /<command> [help|get|test|set|mode|version]
        aliases: [mcs]
        description: Check for new Version.
        permission: mcsync.