name: MCSync
main: mcsync.main
version: '1.1.0'
author: CaptinCornFlakes
website : https://mcsync.live
commands:
    mcsync:
        aliases: [mcs]
        description: Check for new Version.
        usage: /<command>
        permission: mcsync.